=== jzxyouok/taolijie/src/main/webapp/WEB-INF/security-config.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- 定义根节点 -->
    <xs:element name="security">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="login-page" type="xs:string" maxOccurs="1" />
                <xs:element name="rules">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="request" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="path" use="required" />
                                    <xs:attribute name="roles" use="required" />
                                    <xs:attribute name="method" use="optional" default="GET" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jzxyouok/taolijie/src/main/webapp/WEB-INF/security-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<security xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="security-config.xsd">

    <login-page>/login</login-page>

    <rules>
        <request path="/user**" roles="ADMIN STUDENT EMPLOYER"/>

        <request path="/api/job/u" roles="ADMIN STUDENT EMPLOYER"/>
        <request path="/api/sh/u" roles="ADMIN STUDENT EMPLOYER"/>
        <request path="/api/review/u**" roles="ADMIN STUDENT EMPLOYER"/>
        <request path="/api/recommend/u**" roles="ADMIN STUDENT EMPLOYER"/>
        <request path="/api/u**" roles="ADMIN STUDENT EMPLOYER"/>
        <request path="/api/noti**" roles="ADMIN STUDENT EMPLOYER"/>

        <request path="/api/manage**" roles="ADMIN"/>
        <request path="/manage**" roles="ADMIN"/>
    </rules>

</security>
